project_id = "yngoixmvmxdfxokuafjp"

[functions.chat-consultant]
verify_jwt = false

[functions.chat-consultant-v2]
verify_jwt = false

[functions.widget-config]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.knowledge-process]
verify_jwt = false


[functions.diag-v1-query]
verify_jwt = false
