
-- Clear garbage dummy embeddings (they were generated by a non-semantic hash function)
UPDATE public.knowledge_entries SET embedding = NULL WHERE embedding IS NOT NULL;

-- Create hybrid search function (FTS + Vector with Reciprocal Rank Fusion)
CREATE OR REPLACE FUNCTION public.search_knowledge_hybrid(
  search_query text,
  query_embedding vector DEFAULT NULL,
  match_count integer DEFAULT 5
)
RETURNS TABLE(id uuid, title text, content text, type text, source_url text, score double precision)
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
DECLARE
  tsquery_ru tsquery;
  words text[];
  word text;
  tsquery_parts text[];
BEGIN
  -- Build FTS query (same logic as search_knowledge_fulltext)
  words := ARRAY(
    SELECT DISTINCT lower(w) 
    FROM unnest(regexp_split_to_array(lower(search_query), '[^а-яёa-z0-9]+')) AS w
    WHERE length(w) > 2 
      AND w NOT IN ('как', 'что', 'где', 'когда', 'почему', 'какой', 'какая', 'какие', 
                    'это', 'для', 'при', 'над', 'под', 'или', 'так', 'вот', 'вас', 'нас',
                    'можно', 'работает', 'есть', 'ваш', 'ваша', 'ваши', 'мне', 'вам')
  );
  
  IF array_length(words, 1) > 0 THEN
    FOREACH word IN ARRAY words LOOP
      tsquery_parts := array_append(tsquery_parts, word || ':*');
    END LOOP;
    tsquery_ru := to_tsquery('russian', array_to_string(tsquery_parts, ' | '));
  ELSE
    tsquery_ru := plainto_tsquery('russian', search_query);
  END IF;

  RETURN QUERY
  WITH fts_results AS (
    SELECT ke.id, ke.title, ke.content, ke.type, ke.source_url,
           ROW_NUMBER() OVER (ORDER BY ts_rank(ke.search_vector, tsquery_ru) DESC) AS rn
    FROM public.knowledge_entries ke
    WHERE ke.search_vector @@ tsquery_ru
    LIMIT match_count * 3
  ),
  vec_results AS (
    SELECT ke.id, ke.title, ke.content, ke.type, ke.source_url,
           ROW_NUMBER() OVER (ORDER BY ke.embedding <=> query_embedding) AS rn
    FROM public.knowledge_entries ke
    WHERE query_embedding IS NOT NULL 
      AND ke.embedding IS NOT NULL
      AND 1 - (ke.embedding <=> query_embedding) > 0.25
    LIMIT match_count * 3
  ),
  combined AS (
    SELECT COALESCE(f.id, v.id) AS id,
           COALESCE(f.title, v.title) AS title,
           COALESCE(f.content, v.content) AS content,
           COALESCE(f.type, v.type) AS type,
           COALESCE(f.source_url, v.source_url) AS source_url,
           COALESCE(1.0 / (60 + f.rn), 0) + COALESCE(1.0 / (60 + v.rn), 0) AS rrf_score
    FROM fts_results f
    FULL OUTER JOIN vec_results v ON f.id = v.id
  )
  SELECT combined.id, combined.title, combined.content, combined.type, combined.source_url, combined.rrf_score AS score
  FROM combined
  ORDER BY combined.rrf_score DESC
  LIMIT match_count;
END;
$$;
